name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby (rbenv)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler: '2.6.9'
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec spec/unit

      - name: Check gem can be built
        run: gem build lf-cli.gemspec
